//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cats
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> discount { get; set; }
        public string category { get; set; }
        public Nullable<int> idUser { get; set; }
        public string nameImage { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
